### Create student
POST localhost:8080/student
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "age": 21,
  "gender": "MALE",
  "level": "1"
}

### Get all students
GET localhost:8080/student

### GET by id
GET localhost:8080/student/5

### UPDATE student
PUT localhost:8080/student/update/2
Content-Type: application/json

{
  "name": "Toshmat",
  "age": 23,
  "surname": "Toshmatov"
}

### Delete student
DELETE localhost:8080/student/2

### Get by name
GET localhost:8080/student/by-name/Ali

### Get by surname
GET localhost:8080/student/by-surname/Valiyev

### Get by gender
GET localhost:8080/student/by-gender/MALE

### Get by age
GET localhost:8080/student/by-age/20

### Get by level
GET localhost:8080/student/by-level/3

### GET by date
GET localhost:8080/student/by-created_date/2024-10-11

### GET by dates
GET localhost:8080/student/by-created_date/2024-10-01/2024-11-01

### Get by pagination
GET localhost:8080/student/pagination?page=1&size=2

### Get by level
GET localhost:8080/student/pagLevel/3?page=2&size=4

### Get by Gender
GET localhost:8080/student/pagGender/MALE?page=1&size=4
